
window.onload = () => {
    const title = document.getElementById('main-title');
    const area = document.getElementById('content-area');

    title.innerText = "CSS Information Page";
    area.innerHTML = `
        <p>This content was generated by <strong>css.js</strong>.</p>
        <button onclick="go()">Click for Sound</button>
    `;
};

function go() {
    alert("ccs! "); 
}